name: acp_web
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  dart_jsonwebtoken: ^2.12.0
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_portal: ^1.1.4
  flutter_secure_storage: ^9.0.0
  flutter_side_menu: ^0.4.0
  fluttertoast: ^8.2.2
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  path: ^1.8.3
  percent_indicator: ^4.2.3
  pluto_grid: ^7.0.2
  provider: ^6.0.5
  random_password_generator: ^0.2.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^1.10.23
  timelines: ^0.1.0
  url_strategy: ^0.2.0
  uuid: ^4.1.0
  video_player: ^2.7.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/3d_models/
    - assets/videos/
